import mongoose from "mongoose";
const { Schema } = mongoose;

const paymentSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    paperId: { type: Schema.Types.ObjectId, ref: "Paper", required: true, index: true },

    orderId: { type: String, required: true, index: true }, // generated by us
    payherePaymentId: { type: String, default: "", index: true }, // PAYMENTiD
    method: { type: String, default: "" },

    currency: { type: String, default: "LKR" },
    amount: { type: Number, required: true, min: 0 },

    status: {
      type: String,
      // ✅ allow completed also (your DB uses this)
      enum: ["pending", "success", "completed", "failed", "cancelled"],
      default: "pending",
      index: true,
    },

    // PayHere notify fields (optional)
    statusCode: { type: Number, default: 0 }, // payhere status_code
    md5sig: { type: String, default: "" },

    raw: { type: Object, default: {} }, // store payload for debugging
  },
  { timestamps: true }
);

// one successful payment unlocks a paper for a user
paymentSchema.index({ userId: 1, paperId: 1, status: 1 });

const Payment = mongoose.models.Payment || mongoose.model("Payment", paymentSchema);
export default Payment;